version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.20.1
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Check libwasmvm version
          command: |
            LIBWASMVM_VERSION=$(./build/noisd query wasm libwasmvm-version)
            if [[ "$LIBWASMVM_VERSION" != "1.2.0" ]] ; then
              echo "Got unexpected libwasmvm version: $LIBWASMVM_VERSION"
              exit 1
            fi
  tidy:
    docker:
      - image: cimg/go:1.20.1
    steps:
      - checkout
      - run:
          name: Check go mod tidy
          # Use --check or --exit-code when available (Go 1.21?)
          # https://github.com/golang/go/issues/27005
          command: |
            go mod tidy
            CHANGES_IN_REPO=$(git status --porcelain)
            if [[ -n "$CHANGES_IN_REPO" ]]; then
              echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff' for debugging now:"
              git status && git --no-pager diff
              exit 1
            fi
  format-go:
    docker:
      - image: cimg/go:1.20.1
    steps:
      - run:
          name: Install gofumpt
          command: go install mvdan.cc/gofumpt@v0.4.0
      - checkout
      - run:
          name: Check Go formatting with gofmt
          command: |
            [ "$(gofmt -l .)" = "" ] || (gofmt -d . && exit 1)
      - run:
          name: Check Go formatting with gofumpt
          command: |
            [ "$(gofumpt -l .)" = "" ] || (gofumpt -d . && exit 1)

workflows:
  build_and_test:
    jobs:
      - build
      - tidy
      - format-go
